apiVersion: v1
kind: Service
metadata:
  name: processing-service
spec:
  type: NodePort
  selector:
    app: processing-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8082
      nodePort: 30002

