apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  type: NodePort
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8083
      nodePort: 30003

